### ISSUE TITLE
Repeating Sequences

### ISSUE THREAD

**Issue by gollth** [stephaneyfx/enum-iterator#11]
Hi, thanks for this package, its really useful. 

Is there a way to make `Sequence`s repeating, so that Monday follows after Sunday again? 

```rs
use enum_iterator::{next, Sequence};

#[derive(Debug, PartialEq, Sequence)]
enum Day {
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
    Sunday,
}

fn main() {
    assert_eq!(next(&Day::Sunday), Some(Day::Monday));  // failure =(
}
```

**Comment by stephaneyfx** [comment]
Thank you for your kind words. I am glad if this crate is useful to you.

Please let me know if the code below does what you need.

```rust
#![cfg(test)]

use enum_iterator::{all, first, next, Sequence};

#[derive(Clone, Debug, PartialEq, Sequence)]
enum Day {
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
    Sunday,
}

fn next_cycle<T: Sequence>(x: &T) -> Option<T> {
    next(x).or_else(|| first())
}

#[test]
fn it_works() {
    assert_eq!(next_cycle(&Day::Sunday), Some(Day::Monday));
    assert_eq!(all::<Day>().cycle().take(8).last(), Some(Day::Monday));
}
```

**Comment by Tairesh** [comment]
Thank you very much for this package! If you add something like `next_cycle()` consider adding `previous_cycle()` as well. I need it for endless cycling through variants in both directions.

**Comment by gollth** [comment]
Thanks @stephaneyfx for the quick reply. Indeed this already helping a lot. I wonder, though, if this should be the default behaviour of `next()`? Or maybe there is a way of offering another macro (like `RotateEnum`) which has this behaviour on its next:

```rs
use enum_iterator::{all, first, next, RotateEnum};  // name up for debate =)

#[derive(Clone, Debug, PartialEq, RotateEnum)]
enum Day {
    Monday,
    Tuesday,
    Wednesday,
    Thursday,
    Friday,
    Saturday,
    Sunday,
}
```

This way `Sequence` can stay as it is. 

Just and idea, though. I'm fine with the solution you suggested.

**Comment by stephaneyfx** [comment]
@Tairesh, you're very welcome. `1.1.0` was published with these 2 functions. If you're just cycling through variants, have you considered using `all::<Day>().cycle()`? This gives you an `Iterator` that cycles through all the variants.

**Comment by stephaneyfx** [comment]
@gollth, you're welcome. `enum-iterator` needs to provide a way to tell when the last value was reached, and that is achieved by returning `None` from `next`. The non-cycling case needs to be supported, and the cycling case can easily be built on top of it. If you can share how you're using `enum-iterator`, I can try to provide suggestions and assess if more functionality should be provided by `enum-iterator`.

**Comment by gollth** [comment]
I was using it to solve an exercise from [exercism](https://exercism.org/tracks/rust/exercises/scale-generator) which is about musical scales. So I had an enum defining all possible pitch values, which repeat every octave. Something like `all::<Pitch>().cycle()` is exactly what would need. I'm fine with closing this ticket.

Just one note: Maybe it make sense to make this more clear in the documentation. Especially since your example is about `Days` I can see that other people are confused why `None` follows after `next(&Days::Sunday)` 😉

**Comment by stephaneyfx** [comment]
> Just one note: Maybe it make sense to make this more clear in the documentation. Especially since your example is about `Days` I can see that other people are confused why `None` follows after `next(&Days::Sunday)` wink

`1.1.1` was published and clarifies that `next` and `previous` do not cycle.
