### ISSUE TITLE
what's the recommend way to loop the enum

### ISSUE THREAD

**Issue by githik999** [stephaneyfx/enum-iterator#14]
should i use `all..collect() to a vec` or `match next(first())`

sorry if i have asked a stupid question

**Comment by stephaneyfx** [comment]
That is not a stupid question :)

Your second message is correct and shows how to iterate over the variants.

```rust
for day in all::<Day>() { ... }
```

`all` returns an `Iterator` so you can also use all [these](https://doc.rust-lang.org/std/iter/trait.Iterator.html) methods.

**Comment by stephaneyfx** [comment]
You're very welcome!
