### ISSUE TITLE
error while trying to compile the project due to error from `enum-iterator`

### ISSUE THREAD

**Issue by emadbaqeri** [stephaneyfx/enum-iterator#15]
Hey, this is my very simple and compact `Cargo.toml` file, I was using this for experiment purposes but I came up with this error, any idea on this? It would be so much appreciated :)

The code:
```rs
let dummy_variable = DummyEnum::into_enum_iter().collect();
```

```sh
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> /Users/emad/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.1.2/src/lib.rs:82:26
   |
82 | pub const fn cardinality<T: Sequence>() -> usize {
   |                          ^
   |
   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
```

**Comment by stephaneyfx** [comment]
This crate tracks Rust stable and requires Rust 1.61 as of this writing. May you run `rustup update stable` and try again please?

**Comment by stephaneyfx** [comment]
Also, `into_enum_iterator` does not exist anymore in v1. The equivalent code should be:

```rust
use enum_iterator::all;
let dummy_variable = all::<DummyEnum>().collect();
```

**Comment by emadbaqeri** [comment]
Hey @stephaneyfx, thanks for your fast reply, I still have the same issue with my code. [This repository](https://github.com/emadbaqeri/enum-iter-playground) contains the code from which you can reproduce the error.
And also this is the output from `rustup show` to check if I'm running the proper version, which is the latest stable version of `rustup`.
```sh
➜  enum_iter_playground git:(master) rustup show
Default host: aarch64-apple-darwin
rustup home:  /Users/emad/.rustup

installed toolchains
--------------------

stable-aarch64-apple-darwin (default)
nightly-aarch64-apple-darwin

installed targets for active toolchain
--------------------------------------

aarch64-apple-darwin
wasm32-unknown-unknown

active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.61.0 (fe5b13d68 2022-05-18)
```
And also this is the error code again:
```sh
➜  enum_iter_playground git:(master) cargo run 
   Compiling enum-iterator v1.1.2
error[E0658]: trait bounds other than `Sized` on const fn parameters are unstable
  --> /Users/emad/.cargo/registry/src/github.com-1ecc6299db9ec823/enum-iterator-1.1.2/src/lib.rs:82:26
   |
82 | pub const fn cardinality<T: Sequence>() -> usize {
   |                          ^
   |
   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `enum-iterator` due to previous error
```

**Comment by stephaneyfx** [comment]
I cannot reproduce the error you shared when building your repository. There are other errors however. The following code builds fine for me.
```rust
use enum_iterator::all;

#[derive(Debug, enum_iterator::Sequence)]
enum DummyEnum {
    One,
    Two,
    Three,
    Four,
}

fn main() {
    let dummy_variable = all::<DummyEnum>().collect::<Vec<_>>();
    println!("{:?}", dummy_variable);
}
```
Output:
```
[One, Two, Three, Four]
```

May you try this code on your end and let me know how it goes?

**Comment by emadbaqeri** [comment]
Yes, surely. Will let you know about it as soon as get back to my computer

**Comment by emadbaqeri** [comment]
Hey @stephaneyfx, I tried your solution but still getting the same error when compiling. That's weird :/

**Comment by stephaneyfx** [comment]
What is the output of the following commands run in your project directory?
```sh
rustc --version
cargo --version
which rustc
which cargo
```

**Comment by stephaneyfx** [comment]
It looks like you have another version of Rust that was not installed by rustup -- notice how the version reported differs from `rustup show`. Have you installed Rust with brew or some other way besides rustup? You should uninstall this and ensure you use Rust installed by rustup.

**Comment by emadbaqeri** [comment]
> It looks like you have another version of Rust that was not installed by rustup -- notice how the version reported differs from `rustup show`. Have you installed Rust with brew or some other way besides rustup? You should uninstall this and ensure you use Rust installed by rustup.

Yeah, I think we found the problem. actually, you found it. I will give it a try and let you know about the outcome

**Comment by emadbaqeri** [comment]
> It looks like you have another version of Rust that was not installed by rustup -- notice how the version reported differs from `rustup show`. Have you installed Rust with brew or some other way besides rustup? You should uninstall this and ensure you use Rust installed by rustup.

Finally, I have fixed the problem by reinstalling the rust toolchain on my machine.

**Comment by stephaneyfx** [comment]
Thank you for the update and I am glad your issue is solved.
