### ISSUE TITLE
Deriving `Sequence` does not work for empty enums

### ISSUE THREAD

**Issue by brkalmar** [stephaneyfx/enum-iterator#16]
+ rust version: 1.62.0
+ `enum-iterator` version: 1.1.2

The [documentation](https://docs.rs/enum-iterator/1.1.2/enum_iterator/trait.Sequence.html#derivation) states that `Sequence` can be derived for "enumerations without variants".
However, this does not work.

## Minimal example

```rust
use enum_iterator::Sequence;

#[derive(Sequence)]
enum Empty {}
```

### Expected outcome

`Sequence` is successfully implemented for `Empty`.

### Actual outcome

<pre><font color="#F92672"><b>error[E0004]</b></font><b>: non-exhaustive patterns: type `&amp;Empty` is non-empty</b>
 <font color="#66D9EF"><b>--&gt; </b></font>src/lib.rs:3:10
  <font color="#66D9EF"><b>|</b></font>
<font color="#66D9EF"><b>3</b></font> <font color="#66D9EF"><b>| </b></font>#[derive(Sequence)]
  <font color="#66D9EF"><b>| </b></font>         <font color="#F92672"><b>^^^^^^^^</b></font>
  <font color="#66D9EF"><b>|</b></font>
<font color="#A6E22E"><b>note</b></font>: `Empty` defined here
 <font color="#66D9EF"><b>--&gt; </b></font>src/lib.rs:4:6
  <font color="#66D9EF"><b>|</b></font>
<font color="#66D9EF"><b>4</b></font> <font color="#66D9EF"><b>| </b></font>enum Empty {}
  <font color="#66D9EF"><b>| </b></font>     <font color="#A6E22E"><b>^^^^^</b></font>
  <font color="#66D9EF"><b>= </b></font><b>note</b>: the matched value is of type `&amp;Empty`
  <font color="#66D9EF"><b>= </b></font><b>note</b>: references are always considered inhabited
  <font color="#66D9EF"><b>= </b></font><b>note</b>: this error originates in the derive macro `Sequence` (in Nightly builds, run with -Z macro-backtrace for more info)
<font color="#A1EFE4"><b>help</b></font>: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern as shown
  <font color="#66D9EF"><b>|</b></font>
<font color="#66D9EF"><b>3</b></font> <font color="#A6E22E">~ </font>#[derive(Sequence<font color="#A6E22E"> {</font>
<font color="#66D9EF"><b>4</b></font> <font color="#A6E22E">+     _ =&gt; todo!(),</font>
<font color="#66D9EF"><b>5</b></font> <font color="#A6E22E">~ }</font>)]
  <font color="#66D9EF"><b>|</b></font>
</pre>

**Comment by stephaneyfx** [comment]
Fixed in `enum-iterator 1.1.3`.
