### ISSUE TITLE
Sequence doesn't work if enum has f32 or u32, etc.

### ISSUE THREAD

**Issue by namse** [stephaneyfx/enum-iterator#17]
![image](https://user-images.githubusercontent.com/3580430/177759367-cc584146-0277-4768-8fe5-29f4bdbf5150.png)

```rust
#[derive(enum_iterator::Sequence)]
enum Foo {
    A,
    B { a: u32, b: u32 },
    C { a: f32, b: f32 },
}
```

This doesn't work.

**Comment by namse** [comment]
Actually my only use case is, I just want to iterate all enum and their name, not including it's value inside. I tried to make a drop down ui which shows all name of enum and user will select one, then I'm gonna make a default value. that's it.

**Comment by stephaneyfx** [comment]
Based on your use case, the [`strum`](https://docs.rs/strum/0.24.1/strum/index.html) crate may be a better fit. For example, deriving [`IntoStaticStr`](https://docs.rs/strum/0.24.1/strum/derive.IntoStaticStr.html) allows to get each variant as a string, and [`EnumIter`](https://docs.rs/strum/0.24.1/strum/derive.EnumIter.html) allows to iterate over all variants, instantiating any field with `Default::default()`.

**Comment by namse** [comment]
Oh, I checked it and it muse be what I want to find. Thank you for recommendation! I'm gonna close this issue.
