### ISSUE TITLE
When Sequence is derived for ~300 variants, compilation is slow enough that I did not let if finish

### ISSUE THREAD

**Issue by jmesmon** [stephaneyfx/enum-iterator#18]
Build time gets bad even for enums of ~30 variants. Here's a table:

| variants | build time (s) |
|---------|--------------|
| 20 | 0.69 |
| 30 | 1.40 |
| 40 | 2.98 |
| 50 | 6.31 |
| 60 | 11.80 |
| 70 | 20.03 |

Essentially seems like (on my system), build time is doubling for every 10 additional enum variants. At this rate, my 300 variant enum will have a build time of 5.32 years.

Here's the code I used to test this:

```
use enum_iterator::{all, Sequence};

#[derive(Debug, Sequence)]
enum Foo {
    Bar000,
    Bar001,
    Bar002,
    Bar003,
    Bar004,
    Bar005,
    Bar006,
    Bar007,
    Bar008,
    Bar009,
    Bar010,
    Bar011,
    Bar012,
    Bar013,
    Bar014,
    Bar015,
    Bar016,
    Bar017,
    Bar018,
    Bar019,
    Bar020,
    Bar021,
    Bar022,
    Bar023,
    Bar024,
    Bar025,
    Bar026,
    Bar027,
    Bar028,
    Bar029,
    Bar030,
    Bar031,
    Bar032,
    Bar033,
    Bar034,
    Bar035,
    Bar036,
    Bar037,
    Bar038,
    Bar039,
    Bar040,
    Bar041,
    Bar042,
    Bar043,
    Bar044,
    Bar045,
    Bar046,
    Bar047,
    Bar048,
    Bar049,
    Bar050,
    Bar051,
    Bar052,
    Bar053,
    Bar054,
    Bar055,
    Bar056,
    Bar057,
    Bar058,
    Bar059,
    Bar060,
    Bar061,
    Bar062,
    Bar063,
    Bar064,
    Bar065,
    Bar066,
    Bar067,
    Bar068,
    Bar069,
}

fn main() {
    for i in all::<Foo>() {
        println!("foo: {:?}", i);
    }
}
```

I used a vim macro to generate 10 additional variants at a time.

```
% rustc -V
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

```
% cargo tree
enum-iterator-explode v0.1.0 (/Users/cody/p/enum-iterator-explode)
└── enum-iterator v1.1.3
    └── enum-iterator-derive v1.0.2 (proc-macro)
        ├── proc-macro2 v1.0.43
        │   └── unicode-ident v1.0.3
        ├── quote v1.0.21
        │   └── proc-macro2 v1.0.43 (*)
        └── syn v1.0.99
            ├── proc-macro2 v1.0.43 (*)
            ├── quote v1.0.21 (*)
            └── unicode-ident v1.0.3
```

**Comment by stephaneyfx** [comment]
Thank you for reporting this bug.

May you give `1.2.0` a try please? These are the build times I got (dependencies already built):

| Number of variants | 1.1.3 | 1.2.0 |
| ------------------------- | ------- | ------- |
| 100                         | 58 s  | < 1 s  |
| 300                         | ?       | 4 s     |

Is this acceptable for your project?

**Comment by jmesmon** [comment]
Potentially. It looks like it's using some functionality stabilized in rustc 1.63 (`core::array::from_fn`) though, and my project hasn't switched from 1.62 yet, so I haven't been able to actually use it.

**Comment by stephaneyfx** [comment]
If you can't update to Rust 1.63 yet, you should be able to get the fix with the following in your `Cargo.toml` (the fix is entirely in the code generation in `enum-iterator-derive`):
```toml
enum-iterator = "~1.1.3"
enum-iterator-derive = "1.1.0"
```

**Comment by stephaneyfx** [comment]
As [indicated](https://github.com/stephaneyfx/enum-iterator/issues/18#issuecomment-1221396294), the compilation time was drastically reduced.
