### ISSUE TITLE
Guarantee that the iteration order is the same as derive(Ord)

### ISSUE THREAD

**Issue by e00E** [stephaneyfx/enum-iterator#21]
Structs and enums can derive the Ord trait. It would be useful if this crate's iteration order matched the derived Ord implementation. This is likely already the case but I could not find it documented.

Note that for custom Ord implementations this is impossible because you cannot know how they are implemented, but for structs and enums where all fields are recursively Ord derived it should be possible.

**Comment by stephaneyfx** [comment]
Thank you for opening this issue. I'm working on adding documentation on that.

**Comment by stephaneyfx** [comment]
This is what I plan to add to the documentation. In a nutshell, the order yielded by `Sequence::next` should match the order defined by `Ord` with these exceptions:
- Custom implementations of `Sequence` that have a different order.
- Enumerations with custom discriminants where the discriminants are not in increasing order when going through the variants from top to bottom.

Does that address your request?

> Values are yielded in the following order. Comparisons between values are based on their relative order as yielded by next; an element yielded after another is considered greater.
> - For primitive types, in increasing order.
> - For arrays and tuples, in lexicographic order of the sequence of their elements.
> - When derived for an enumeration, in variant definition order.
> - When derived for a structure, in lexicographic order of the sequence of its fields taken in definition order.

**Comment by e00E** [comment]
Thank you for making this crate.

> Does that address your request?

That sounds great. Maybe add a sentence that this matches the compiler's Ord derives because it might not be obvious when reading this description or for people unaware of how Ord derive works. For reference, Ord derives are documented in `std::cmp::Ord` .

**Comment by stephaneyfx** [comment]
The reason I didn't specify the order matches `Ord` is because that isn't always true. This is an example where the order would not match, because the discriminants don't increase from top to bottom:
```rust
#[derive(Eq, Ord, PartialEq, PartialOrd, Sequence)]
enum Foo {
    A = 1,
    B = 0,
}
```

I'll try to modify the wording to indicate when the order does match `Ord`.

**Comment by stephaneyfx** [comment]
Done in 2ed528bb4450c300099e01a58ce813575c6ae0a7.
