### ISSUE TITLE
Optimization potential for contiguous c-style enums

### ISSUE THREAD

**Issue by e00E** [stephaneyfx/enum-iterator#22]
Consider a c-style enum over a contiguous sequence of values (no gaps). In this case iterating over the values can be implemented by starting at the lowest element and incrementing the underlying integer type until we reach the highest element. In assembly this would be an increment and a comparison against a constant.

The way this crate derives `Sequence` is suboptimal in terms of the generated assembly. In the following code I compare it to what a derive of [`bytemuck::Contiguous`](https://docs.rs/bytemuck/latest/bytemuck/trait.Contiguous.html) generates.

```rust
use bytemuck::Contiguous;
use enum_iterator::Sequence;

#[derive(Copy, Clone, Contiguous, Sequence)]
#[repr(u8)]
pub enum E {
    E0,
    E1,
    E2,
}

impl E {
    pub fn next_bytemuck(&self) -> Option<Self> {
        Self::from_integer(*self as u8 + 1)
    }

    pub fn next_enum_iterator(&self) -> Option<Self> {
        self.next()
    }
}
```

The assembly for bytemuck is

```asm
    movzx eax, byte ptr [rdi]
    inc al
    ret
```

and for enum-iterator

```asm
    movzx eax, byte ptr [rdi]
    test eax, eax
    je .LBB1_1

    cmp eax, 1
    jne .LBB1_4

    mov al, 2
    ret

.LBB1_1:
    mov al, 1
    ret

.LBB1_4:
    mov al, 3
    ret
```

The enum-iterator version is linear with the number of enum variants and uses a jump table. I didn't check the derive macro code but it probably generates a match over all variants. This is more work for the compiler because of the larger amount of Rust code and worse assembly.

An easy fix might be to rewrite the match statement as in https://github.com/rust-lang/rust/issues/85841 . This yields the best assembly but still generates more Rust code than necessary.

**Comment by stephaneyfx** [comment]
This is the assembly I get for `bar` (on Linux) with rust 1.67.1 and `enum-iterator` 1.3.0:
```rust
use enum_iterator::Sequence;

#[derive(Clone, Copy, Sequence)]
#[repr(u8)]
pub enum Foo {
    A,
    B,
    C,
}

pub fn bar(x: &Foo) -> Option<Foo> {
    enum_iterator::next(x)
}
```

```sh
RUSTFLAGS="--emit asm" cargo build --release
```

```asm
    movzbl  (%rdi), %eax
    incb    %al
    retq
```

**Comment by e00E** [comment]
Surprisingly, this depends on the LTO [setting](https://doc.rust-lang.org/cargo/reference/profiles.html#lto) . With `lto = false` I get the good assembly but with `"thin"` or `"fat"` I get the bad assembly. That seems like a rustc bug because LTO made the assembly worse when I would expect it to only make it better. I'll report it there.

Even if the optimization was consistent, this issue still has merit because of the reduction in generated rust code. The generated match statement is linear with the number of enum variants, while the smarter contiguous specific implementation is constant. Although I'm not sure how much extra code complexity this is in this crate, so it might not be worth doing.

**Comment by stephaneyfx** [comment]
Thank you very much for digging into this and identifying the cause of the difference in the assembly.

The code generated by the derive macro used to be much simpler when this crate only supported C-like enumerations. With the support of structured types, a goal was to try to keep the derive logic simple and unified, avoiding special cases. I agree that this relies more on the optimizer.

I would rather not introduce a special case in the derive macro for C-like enumerations without gaps in the discriminants. I am open to revisiting if the performance proves to be a bottleneck.

**Comment by e00E** [comment]
It's totally reasonable to not implement this optimization in this crate. If it really matters, you can always manually implement Sequence based on a Contiguous derive. Whether the performance matters is going to depend on the use case. A practical example where it might start mattering is if you use Sequence with enums that have a lot of variants. Maybe you're autogenerating an enum with 10000 variants or something like that. That could matter for compile and runtime performance. I have not benchmarked anything.

**Comment by stephaneyfx** [comment]
I published a new version that substantially reduces compilation time of the generated code, and simplifies it to some extent when variants don't have fields. There is still room for improvement, and it still does not guarantee that the code gets optimized as discussed earlier in this thread.

If one has performance issues (compilation or runtime), please re-open or create a new issue.
