### ISSUE TITLE
Performance issues with larger (medium sized?) enums

### ISSUE THREAD

**Issue by pietervandermeer** [stephaneyfx/enum-iterator#23]
Having 2 enums of about 50 elements and adding ```#[derive(Sequence)]``` to them slows down compilation, and rust-analyzer  almost to a crawl. Even on a 2022 i7 quad core. The usability of this crate is awesome, however. But I think if I have to add one more derive Sequence, I'll have to avoid it.... Is there anything that can be done about this?

Running:
toolchain 1.63-x86_64-unknown-linux-gnu
rustc 1.67.1

**Comment by pietervandermeer** [comment]
Oh nevermind. Just moved from enum-iter version 1.1.1 to 1.3.0, and performance is ok again. Closing.

**Comment by stephaneyfx** [comment]
Glad to hear the performance is now acceptable. Indeed 1.2.0 addressed a performance issue regarding compilation time.
