### ISSUE TITLE
Add an `ord()` function to get the enum variant index

### ISSUE THREAD

**Issue by barbagus** [stephaneyfx/enum-iterator#29]
The current API can tell use the cardinality of an `enum` but lacks a way to get the "ordinality" (sequence index).

My use case is something like that:
```rust

#[derive(Sequence)]
pub enum Color {
    Red,
    Green,
    Blue,
    Yellow,
    Purple,
    Orange,
}

fn has_duplicate(colors: Vec<Color>) -> bool {
    let mut memo = [false; cardinality::<Color>()];
    for color in colors {
        if memo[ord(color)] {
            return true;
        }
        memo[ord(color)] = true;
    }
    false
}
```
In a nutshell: taking advantage of `cardinality` known at compile time to build static arrays of same dimension and then being able to index into such an array.

In the mean time, I did implement it as a `usize::from()` with a big `match`... which means I need to be careful to keep both (the `from()` and the `enum` definition) in sync.

I confess I have not much read the code nor attempt an implementation. I could if this feature seems of interest.

**Comment by stephaneyfx** [comment]
Does that do what you want?
```rust
use enum_iterator::Sequence;

#[derive(Clone, Copy, Sequence)]
pub enum Color {
    Red,
    Green,
    Blue,
    Yellow,
    Purple,
    Orange,
}

pub fn has_duplicate(colors: Vec<Color>) -> bool {
    let mut memo = [false; enum_iterator::cardinality::<Color>()];
    for color in colors {
        if memo[color as usize] {
            return true;
        }
        memo[color as usize] = true;
    }
    false
}

#[cfg(test)]
mod tests {
    use crate::{has_duplicate, Color};

    #[test]
    fn has_duplicate_returns_true_if_dup_found() {
        assert!(has_duplicate(vec![Color::Red, Color::Green, Color::Red]));
    }

    #[test]
    fn has_duplicate_returns_false_if_no_dup_found() {
        assert!(!has_duplicate(vec![Color::Red, Color::Green]));
    }
}
```

**Comment by barbagus** [comment]
It does indeed... I did'nt know we could do that. Although I want to say sorry for the disturbance then, maybe there is still a case for less trivial cases like stucts or cases where explicit discriminent are used, but thqt will do for me. Thanks.

**Comment by stephaneyfx** [comment]
> Although I want to say sorry for the disturbance then

Don't be sorry, there was no disturbance. I am glad to answer questions regarding this crate.

The solution casting to `usize` also works with custom discriminants.
