### ISSUE TITLE
Iteratorion order

### ISSUE THREAD

**Issue by latot** [stephaneyfx/enum-iterator#31]
Hi! thx for this crate :)

This is not specified on the docs, but is the iteration order guarantee? if not, is possible to do it?

If is guarantee, pls write it in the docs :) .

Thx!

**Comment by stephaneyfx** [comment]
> Hi! thx for this crate :)

Hi! You're welcome :)

The iteration order is described in the documentation of [`Sequence::next`](https://docs.rs/enum-iterator/latest/enum_iterator/trait.Sequence.html#tymethod.next):
> Values are yielded in the following order. Comparisons between values are based on their relative order as yielded by next; an element yielded after another is considered greater.
>
> - For primitive types, in increasing order (same as Ord).
> - For arrays and tuples, in lexicographic order of the sequence of their elements.
> - When derived for an enumeration, in variant definition order.
> - When derived for a structure, in lexicographic order of the sequence of its fields taken in definition order.
>
>The order described above is the same as Ord if any custom Sequence implementation follows Ord and any enumeration has its variants defined in increasing order of discriminant.

Does that answer your question?

**Comment by latot** [comment]
Hi! sorry I thought I answered this, yes that answer the question.

Maybe, due to the nature of this lib, would be good a link or something in the main page, or in a easier place to see it.

**Comment by stephaneyfx** [comment]
Hi! No worries. I am glad that answered your question.
