### ISSUE TITLE
No WASM support

### ISSUE THREAD

**Issue by Pfeil** [stephaneyfx/enum-iterator#6]
enum-iterator is a perfect fit for my use case. Unfortunately neither enum-iterator nor strum seem to work with WASM. Both compile, but then crash on runtime as soon as an enum iterator is created. It is the same issue I always have if I forget to enable a feature to enable wasm support. Unfortunately I do not have any details about the problem, as the browser shows just useless error messages about something happening in wasm.js.

Do you think it is possible to add wasm support? My macro knowledge is pretty limited, but if the task is not too large it might be an option for me to help with this, as long as I have a hint what needs to be done. Currently I have no clue what causes the problem. I am building a wasm app with yew and stable rust.

**Comment by stephaneyfx** [comment]
What error did you get exactly?

I tried a simple project using `enum-iterator`, built it targetting `wasm32-unknown-unknown` and it ran in the browser without any issue.

The project contains this single rs file:
```rust
use enum_iterator::IntoEnumIterator;
use wasm_bindgen::prelude::wasm_bindgen;

#[derive(Debug, IntoEnumIterator)]
enum Foo {
    A,
    B,
}

#[wasm_bindgen]
extern "C" {
    fn alert(s: &str);
}

#[wasm_bindgen]
pub fn say_all_variants() {
    let s = Foo::into_enum_iter()
        .map(|v| format!("{:?}, ", v))
        .collect::<String>();
    alert(&s);
}
```

`wasm-bindgen --target web ...` was used to generate the glue and the code ran in the browser when opening the following page, showing an alert box with the variants listed as expected:
```html
<html>
  <body>
    <script type="module">
      import init, { say_all_variants } from './pkg/enum_iterator_wasm_example.js';
      async function run() {
        await init();
        say_all_variants();
      }

      run();
    </script>
    <p>Hello there!</p>
  </body>
</html>
```

**Comment by Pfeil** [comment]
Ah yes, my fault, sorry. It works now. My example wasn't minimal in that I have overseen a usage of a Display implementation, which caused the problem. The panic was looking like this, even though I have a panic hook set up:

```
Uncaught Error: undefined  wasm_bg.wasm:388243:1
    <anonym> http://localhost:8080/wasm_bg.wasm:388243
    <anonym> http://localhost:8080/wasm_bg.wasm:229107
    ...
```

I am not sure what exactly is the problem. My Display implementation causing the problem used the Display implementation for String, but when I use `{:?}` to Display the string, it works. But it is definitely not related to this crate, and I have workarounds. It works perfectly fine now, sorry for the trouble :D (and thanks, this crate is really helpful)

**Comment by stephaneyfx** [comment]
Don't be sorry, it was no trouble. I'm glad you got it to work and thank you for the kind words.
